網站資訊系統/VS/素材/HW7/08PartialView/HW7Project/Models/Members.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Security.Cryptography;

namespace HW7Project.Models
{
    public class Members
    {

        [Key]
        [DisplayName("會員編號")]
        public int MemberID { get; set; }

        [DisplayName("姓名")]
        [StringLength(100)]
        [Required]
        public string MemberName { get; set; }

        [DisplayName("照片")]
        [MaxLength]
        public string MemberPhotoFile { get; set; }

        [DisplayName("生日")]
        [Required]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public DateTime MemberBirthday { get; set; }

        [DisplayName("建立日期")]
        [Required]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public DateTime CreatedDate { get; set; }


        [DisplayName("帳號")]
        [Required]
        [StringLength(20)]
        [CheckAccount]
        public string Account { get; set; }

        //field
        string password;  //定義一個password的field

        [DisplayName("密碼")]
        [Required]
        [DataType(DataType.Password)]

        public string Password
        {
            get
            {
                return password;

            }
            set
            {
                password = getHashPassword(value);
            }

        }

        public static string getHashPassword(string pw)
        {
            byte[] hashValue;
            string result = "";

            System.Text.UnicodeEncoding ue = new System.Text.UnicodeEncoding();

            byte[] pwBytes = ue.GetBytes(pw);

            SHA256 shHash = SHA256.Create();

            hashValue = shHash.ComputeHash(pwBytes);

            foreach (byte b in hashValue)
            {
                result += b.ToString();
            }

            return result;
        }

        //自訂驗證規則的寫法
        public class CheckAccount : ValidationAttribute
        {

            public CheckAccount()
            {
                ErrorMessage = "此帳號有人使用";
            }
            public override bool IsValid(object value)
            {
                if (value == null)
                    value = "aa";

                HW7ProjectContext db = new HW7ProjectContext();

                var account = db.Members.Where(m => m.Account == value.ToString()).FirstOrDefault();

                return (account==null)?true:false;
            }
        }

        
    }
}

網站資訊系統/VS/素材/HW7/08PartialView/HW7Project/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HW7Project.Models;
using PagedList;
using System.Configuration;

namespace HW7Project.Controllers
{
    [LoginCheck]
    public class MembersController : Controller
    {
        private HW7ProjectContext db = new HW7ProjectContext();

        // GET: Members
        public ActionResult Index(int page=1)
        {
            var members = db.Members.ToList();

            int pagesize = 15;


            var pagedList = members.ToPagedList(page, pagesize);

            return View(pagedList);
        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Members members = db.Members.Find(id);
            if (members == null)
            {
                return HttpNotFound();
            }
            return PartialView(members);
        }

        // GET: Members/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: Members/Create
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MemberID,MemberName,MemberPhotoFile,MemberBirthday,CreatedDate,Account,Password")] Members members,HttpPostedFileBase photo)
        {
            if (photo != null)
            {
                if(photo.ContentLength>0)
                {
                    string extensionName = System.IO.Path.GetExtension(photo.FileName);
                    if (extensionName == ".jpg" || extensionName == ".png")
                    {
                        photo.SaveAs(Server.MapPath("~/MemberPhotos/" + members.Account + extensionName));

                        members.MemberPhotoFile = members.Account +  extensionName;
                    }
                }
            }

            if (ModelState.IsValid)
            {
                db.Members.Add(members);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Members members = db.Members.Find(id);
            if (members == null)
            {
                return HttpNotFound();
            }
            return View(members);
        }

        // POST: Members/Edit/5
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Members members)
        {
            string sql = "update members set MemberName=@MemberName, MemberBirthday=@MemberBirthday where MemberID=@MemberID";

            SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["HW7ProjectConnection"].ConnectionString);
            SqlCommand cmd = new SqlCommand(sql, conn);

            cmd.Parameters.AddWithValue("@MemberName",members.MemberName);
            cmd.Parameters.AddWithValue("@MemberBirthday", members.MemberBirthday);
            cmd.Parameters.AddWithValue("@MemberID", members.MemberID);
            
       

            conn.Open();
            try
            {
                cmd.ExecuteNonQuery();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            conn.Close();

            return View(members);

            //if (ModelState.IsValid)
            //{
            //    db.Entry(members).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Members members = db.Members.Find(id);
            if (members == null)
            {
                return HttpNotFound();
            }
            return View(members);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Members members = db.Members.Find(id);
            db.Members.Remove(members);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

網站資訊系統/VS/素材/HW7/08PartialView/HW7Project/Views/Members/Create.cshtml
@model HW7Project.Models.VMMember

@{
    ViewBag.Title = "Create";
    var CreatedDate = DateTime.Today.ToShortDateString();
    Layout = "~/Views/Shared/_Layout_Manager.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Members", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>VMMember</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MemberName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberPhotoFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.MemberPhotoFile, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.TextBoxFor(Model => Model.MemberPhotoFile, new {type="file",@class= "form-control",name="photo" })*@
                <input id="photo" type="file" class="form-control" name="photo" />
                @Html.ValidationMessageFor(model => model.MemberPhotoFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberBirthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberBirthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberBirthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <input id="CreatedDate" type="hidden" name="CreatedDate" value="@CreatedDate" />
        @*<div class="form-group">
                @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                   @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                </div>
            </div>*@



        <div class="form-group">
            @Html.LabelFor(model => model.Account, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
                @*<span class="text-danger">@ViewBag.Error</span>*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

網站資訊系統/VS/素材/HW7/08PartialView/HW7Project/Views/Members/Details.cshtml
@model HW7Project.Models.Members

@{
//ViewBag.Title = "Details";
}



<div class="p-3">

    <div class="card border-info">
        <div class="card-header bg-info text-white">
            <h3>@Html.DisplayFor(model => model.MemberName)</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                    <h4>生日:@Html.DisplayFor(model => model.MemberBirthday)</h4>
                    <h4>
                        帳號:@Html.DisplayFor(model => model.Account)
                    </h4>
                    <h4> 密碼:●●●●●●●●●●●●●●●●●●●●●●●●●●</h4>
                </div>
                <div class="col-md-4">
                   @{ 
                        var photo = Model.MemberPhotoFile == null ? "defaultPhoto.png" : Model.MemberPhotoFile;

                    }

                    <img src="~/MemberPhotos/@photo" class="img-thumbnail" />
                 
                </div>
            </div>
        </div>
        <div class="card-footer text-right bg-info text-white">
            @Html.DisplayFor(model => model.CreatedDate)
        </div>
    </div>

   
</div>

網站資訊系統/VS/素材/HW7/08PartialView/HW7Project/Views/Members/Edit.cshtml
@model HW7Project.Models.Members

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout_Manager.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Members</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MemberID)
    
        <div class="form-group">
            @Html.LabelFor(model => model.MemberName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberName, "", new { @class = "text-danger" })
            </div>
        </div>

     

        <div class="form-group">
            @Html.LabelFor(model => model.MemberBirthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberBirthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberBirthday, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                <span class="text-danger">@ViewBag.Error</span>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

網站資訊系統/VS/素材/HW7/08PartialView/HW7Project/Views/Members/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@*@model IEnumerable<HW7Project.Models.VMMember>*@

@model IPagedList<HW7Project.Models.Members>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Manager.cshtml";
}

<h2>會員資料列表</h2>

<p class="text-right">
    @Html.ActionLink("新增會員資料", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.MemberID)*@
                @Html.DisplayNameFor(model => model.FirstOrDefault().MemberID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().MemberName)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().MemberBirthday)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().CreatedDate)
            </th>

            <th>資料管理</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MemberID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MemberName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.MemberBirthday)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>

            <td>
                @Html.ActionLink("編輯", "Edit", new { id = item.MemberID }, new { @class = "btn btn-info btn-sm" })
                @*@Html.ActionLink("詳細", "Details", new { id = item.MemberID }, new { @class = "btn btn-success btn-sm" })*@
                <button type="button" title="@item.MemberID" class="btn btn-success btn-sm btnDetail" data-toggle="modal" data-target="#exampleModal">
                    詳細
                </button>
            </td>
        </tr>
    }

</table>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">會員詳細資料</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
           
        </div>
    </div>
</div>
@section scripts{
    <script>
        $('.pagination-container').addClass("d-flex justify-content-center");
        $('.pagination-container>ul>li').removeClass().addClass("page-item");
        $('.pagination-container a').addClass("page-link");
        

        $('.btnDetail').click(function (evt) {
            //console.log("/Members/Details/" + evt.target.title);
            $('#exampleModal .modal-body').load("/Members/Details/" + evt.target.title);
        });
       
     

    </script>
}